/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import javax.swing.JSplitPane;
import javax.swing.JOptionPane;
import model.vaccinationsystem.CovidVaccinationSystem;


/**
 *
 * @author gayat
 */
public class SystemAdminPanel extends javax.swing.JPanel {
        private javax.swing.JSplitPane splitPane;
        private CovidVaccinationSystem covidVaccinationSystem;


    /**
     * Creates new form SystemAdmin
     */
    public SystemAdminPanel(JSplitPane splitPane, CovidVaccinationSystem covidVaccinationSystem) {
        initComponents();
        this.splitPane = splitPane;
        this.covidVaccinationSystem = covidVaccinationSystem;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        tbnPersonList = new javax.swing.JButton();
        btnEncList = new javax.swing.JButton();
        btnSysAdminHosp = new javax.swing.JButton();
        btnSysDoc = new javax.swing.JButton();

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setText("System Admin");

        tbnPersonList.setText("Community ");
        tbnPersonList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnPersonListActionPerformed(evt);
            }
        });

        btnEncList.setText("Covid Charity");
        btnEncList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEncListActionPerformed(evt);
            }
        });

        btnSysAdminHosp.setText("Vaccine Provider List");
        btnSysAdminHosp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSysAdminHospActionPerformed(evt);
            }
        });

        btnSysDoc.setText("Medical Center List");
        btnSysDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSysDocActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(390, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnSysAdminHosp)
                            .addComponent(btnSysDoc)
                            .addComponent(tbnPersonList, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEncList))
                        .addGap(337, 337, 337))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblTitle)
                        .addGap(373, 373, 373))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnEncList, btnSysAdminHosp, btnSysDoc, tbnPersonList});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblTitle)
                .addGap(53, 53, 53)
                .addComponent(btnSysAdminHosp)
                .addGap(35, 35, 35)
                .addComponent(btnSysDoc)
                .addGap(31, 31, 31)
                .addComponent(tbnPersonList, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnEncList)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnEncList, btnSysAdminHosp, btnSysDoc, tbnPersonList});

    }// </editor-fold>//GEN-END:initComponents

    private void tbnPersonListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnPersonListActionPerformed
        // TODO add your handling code here:
//        PatientPanel patientList = new PatientPanel(healthCareSystem);
//        this.splitPane.setRightComponent(patientList);

        
    }//GEN-LAST:event_tbnPersonListActionPerformed

    private void btnSysDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSysDocActionPerformed
        // TODO add your handling code here:
//        NursePanel doctorList = new NursePanel(healthCareSystem);
//        this.splitPane.setRightComponent(doctorList);


    }//GEN-LAST:event_btnSysDocActionPerformed

    private void btnSysAdminHospActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSysAdminHospActionPerformed
        // TODO add your handling code here:
        VaccineManufacturerListPanel vaccinationManufacturerPanel = new VaccineManufacturerListPanel(covidVaccinationSystem);
        this.splitPane.setRightComponent(vaccinationManufacturerPanel);
    }//GEN-LAST:event_btnSysAdminHospActionPerformed

    private void btnEncListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEncListActionPerformed
        // TODO add your handling code here:
//        SysEncounter encounterList = new SysEncounter(healthCareSystem);
//        splitPane.setRightComponent(encounterList);

    }//GEN-LAST:event_btnEncListActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEncList;
    private javax.swing.JButton btnSysAdminHosp;
    private javax.swing.JButton btnSysDoc;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JButton tbnPersonList;
    // End of variables declaration//GEN-END:variables
}
